version: '3' 
services:
  web:
    image: "redis-tryout"
    ports:
      - "5000:5000"
    links:
      - "redis"
    environment:
      - ASPNETCORE_ENVIRONMENT=container

  redis:
    image: "redis:alpine"